name: Hourly Expense Sync

on:
  schedule:
    - cron: '0 */8 * * *'  # Run every 8 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-expenses:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      working-directory: ./utils
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run expense sync script
      working-directory: ./utils
      run: python script.py 
